version: '3.9'

services:
  app:
    build:
      context: .
    # override the command in the Dockerfile which would run in uwsgi. Locally, we want to 
    # run it using the django management server.
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG=1
